//
//  LoginRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 11/09/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class LoginRouter {

    weak var viewController: UIViewController?

    deinit {
        print("deinit LoginRouter")
    }

    static func createModule() -> UIViewController {

        let storyboard = getStoryBoard(.userAuthentication)
        let view = storyboard.instantiateViewController(ofType: LoginViewController.self)
        
        let interactor = LoginInteractor()
        let router = LoginRouter()
        let presenter = LoginPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}

extension LoginRouter: LoginWireframeProtocol {
    func gotoHome() {
        let controller = HomeRouter.createModule()
        self.viewController?.navigationController?.pushViewController(controller, animated: true)
    }
    

}
