//
//  LoginScreenViewControllerProtocols.swift
//  PA Store
//
//  Created Haroon Shoukat on 18/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import Foundation

// MARK: Wireframe -
protocol LoginScreenViewControllerWireframeProtocol: class {

    func gotoMultiStoreScreen(stores: [AssignedStore])
}
// MARK: Presenter -
protocol LoginScreenViewControllerPresenterProtocol: class {

    var interactor: LoginScreenViewControllerInteractorInputProtocol? { get set }

    var userData: LoginResponse? {get set}
    
    func viewDidLoad()
    
    func loginUser(params: [String: Any])
    
    func gotoMultiStore(stores: [AssignedStore])
    
    
}

// MARK: Interactor -
protocol LoginScreenViewControllerInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getLoginSuccess(_ userData: LoginResponse?)
    func getLoginFailure(_ errorMessage: String)
}

protocol LoginScreenViewControllerInteractorInputProtocol: class {

    var presenter: LoginScreenViewControllerInteractorOutputProtocol? { get set }
    func loginUser(params: [String: Any])
    /* Presenter -> Interactor */
}

// MARK: View -
protocol LoginScreenViewControllerViewProtocol: class {

    var presenter: LoginScreenViewControllerPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func showLoader()
    func hideLoader()

    func setupEnglishView()
    func setupArabicView()
    
    func showErrorMessage(_ errorMessage: String)
    func showSuccessMessage(_ message: String)
}
