//
//  LoginRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 11/09/2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class LoginRouter {

    weak var viewController: UIViewController?

    deinit {
        printNgi("deinit LoginRouter")
    }

    static func createModule() -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let view = LoginViewController(nibName: nil, bundle: nil)
        let interactor = LoginInteractor()
        let router = LoginRouter()
        let presenter = LoginPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}

extension LoginRouter: LoginWireframeProtocol {

}
