//
//  LoginScreenViewControllerRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 18/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class LoginScreenViewControllerRouter {

    weak var viewController: UIViewController?

    deinit {
        print("deinit LoginScreenViewControllerRouter")
    }

    static func createModule() -> UIViewController {
        let storyboard = getStoryBoard(.userAuthentication)
        let view = storyboard.instantiateViewController(ofType: LoginScreenViewControllerViewController.self)
        
        let interactor = LoginScreenViewControllerInteractor()
        let router = LoginScreenViewControllerRouter()
        let presenter = LoginScreenViewControllerPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view        
        return view
    }
}

extension LoginScreenViewControllerRouter: LoginScreenViewControllerWireframeProtocol {
    func gotoMultiStoreScreen(stores: [AssignedStore]) {
        let vc = MultiStoreScreenRouter.createModule(stores: stores)
        self.viewController?.navigationController?.setViewControllers([vc], animated: true)
    }
}
