//
//  UploadImageScreenRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 23/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class UploadImageScreenRouter {

    weak var viewController: UIViewController?

    deinit {
        printNgi("deinit UploadImageScreenRouter")
    }

    static func createModule() -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let view = UploadImageScreenViewController(nibName: nil, bundle: nil)
        let interactor = UploadImageScreenInteractor()
        let router = UploadImageScreenRouter()
        let presenter = UploadImageScreenPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}

extension UploadImageScreenRouter: UploadImageScreenWireframeProtocol {

}
