//
//  UploadImageScreenRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 23/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class UploadImageScreenRouter {

    weak var viewController: UIViewController?

    deinit {
        printNgi("deinit UploadImageScreenRouter")
    }

    static func createModule(product: DataProduct) -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let storyboard = getStoryBoard(.userAuthentication)
        let view = storyboard.instantiateViewController(ofType: UploadImageScreenViewController.self)
        
        let interactor = UploadImageScreenInteractor()
        let router = UploadImageScreenRouter()
        let presenter = UploadImageScreenPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        presenter.product = product
        return view
    }
}

extension UploadImageScreenRouter: UploadImageScreenWireframeProtocol {
    func gotoHome() {
        let vc = HomeScreenRouter.createModule()
        self.viewController?.navigationController?.setViewControllers([vc], animated: true)
    }
    

}
