//
//  HomeScreenProtocols.swift
//  PA Store
//
//  Created Haroon Shoukat on 04/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import Foundation

// MARK: Wireframe -
protocol HomeScreenWireframeProtocol: class {

}
// MARK: Presenter -
protocol HomeScreenPresenterProtocol: class {

    var interactor: HomeScreenInteractorInputProtocol? { get set }

    func viewDidLoad()
}

// MARK: Interactor -
protocol HomeScreenInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol HomeScreenInteractorInputProtocol: class {

    var presenter: HomeScreenInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol HomeScreenViewProtocol: class {

    var presenter: HomeScreenPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func showLoader()
    func hideLoader()

    func setupEnglishView()
    func setupArabicView()
}
