//
//  HomeScreenProtocols.swift
//  PA Store
//
//  Created Haroon Shoukat on 04/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import Foundation

// MARK: Wireframe -
protocol HomeScreenWireframeProtocol: class {
    func gotoLoginPage()
    func gotoSetting()
    func gotoProductDetailPage(product: GetProductResponse)
}
// MARK: Presenter -
protocol HomeScreenPresenterProtocol: class {

    var interactor: HomeScreenInteractorInputProtocol? { get set }

    func viewDidLoad()
    
    func gotoLoginPage()
    func gotoSetting()
    func gotoProductDetailPage(product: GetProductResponse)
    
    func getProductDetail(refNumber: String)
    
}

// MARK: Interactor -
protocol HomeScreenInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    
    func getProductSuccess(_ product: GetProductResponse)
    func getProductFailure(_ errorMessage: String)
}

protocol HomeScreenInteractorInputProtocol: class {

    var presenter: HomeScreenInteractorOutputProtocol? { get set }

    func getProductDetail(refNumber: String)
    
    /* Presenter -> Interactor */
}

// MARK: View -
protocol HomeScreenViewProtocol: class {

    var presenter: HomeScreenPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func showLoader()
    func hideLoader()

    func showAlertView(message: String)
    func setupEnglishView()
    func setupArabicView()
}
