//
//  HomeScreenRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 04/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class HomeScreenRouter {

    weak var viewController: UIViewController?

    deinit {
        print("deinit HomeScreenRouter")
    }

    static func createModule() -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let storyboard = getStoryBoard(.userAuthentication)
        let view = storyboard.instantiateViewController(ofType: HomeScreenViewController.self)
        
        let interactor = HomeScreenInteractor()
        let router = HomeScreenRouter()
        let presenter = HomeScreenPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        

        return view
    }
}

extension HomeScreenRouter: HomeScreenWireframeProtocol {
    func gotoSetting() {
        let vc = SettingRouter.createModule()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func gotoLoginPage() {
        let vc = LoginScreenViewControllerRouter.createModule()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func gotoProductDetailPage(product: GetProductResponse) {
        
        if product.datt != nil{
            let vc = ProductDetailScreenRouter.createModule(product: product.datt!)
            self.viewController?.navigationController?.pushViewController(vc, animated: true)
        }
    }
}
