//
//  SettingRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 29/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class SettingRouter {

    weak var viewController: UIViewController?

    deinit {
        printNgi("deinit SettingRouter")
    }

    static func createModule() -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let storyboard = getStoryBoard(.userAuthentication)
        let view = storyboard.instantiateViewController(ofType: SettingViewController.self)
        
        let interactor = SettingInteractor()
        let router = SettingRouter()
        let presenter = SettingPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}

extension SettingRouter: SettingWireframeProtocol {
    func gotoLogin() {
        let vc = LoginScreenViewControllerRouter.createModule()
        self.viewController?.navigationController?.setViewControllers([vc], animated: true)
    }
    
    func gotoMultiStoreScreen(stores: [AssignedStore]) {
        let vc = MultiStoreScreenRouter.createModule(stores: stores)
        self.viewController?.navigationController?.setViewControllers([vc], animated: true)
    }
}
