//
//  SettingProtocols.swift
//  PA Store
//
//  Created Haroon Shoukat on 29/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import Foundation

// MARK: Wireframe -
protocol SettingWireframeProtocol: class {

}
// MARK: Presenter -
protocol SettingPresenterProtocol: class {

    var interactor: SettingInteractorInputProtocol? { get set }

    func viewDidLoad()
}

// MARK: Interactor -
protocol SettingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SettingInteractorInputProtocol: class {

    var presenter: SettingInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol SettingViewProtocol: class {

    var presenter: SettingPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func showLoader()
    func hideLoader()

    func setupEnglishView()
    func setupArabicView()
}
