//
//  MultiStoreScreenRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 19/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class MultiStoreScreenRouter {

    weak var viewController: UIViewController?

    deinit {
        printNgi("deinit MultiStoreScreenRouter")
    }

    static func createModule(stores: [AssignedStore]) -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let storyboard = getStoryBoard(.userAuthentication)
        let view = storyboard.instantiateViewController(ofType: MultiStoreScreenViewController.self)
        
        let interactor = MultiStoreScreenInteractor()
        let router = MultiStoreScreenRouter()
        let presenter = MultiStoreScreenPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        presenter.stores = stores
        return view
    }
}

extension MultiStoreScreenRouter: MultiStoreScreenWireframeProtocol {
    func gotoHomePage() {
        let vc = HomeScreenRouter.createModule()
        self.viewController?.navigationController?.setViewControllers([vc], animated: true)
    }
}
