//
//  ProductDetailScreenRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 23/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class ProductDetailScreenRouter {

    weak var viewController: UIViewController?

    deinit {
        printNgi("deinit ProductDetailScreenRouter")
    }

    static func createModule() -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let view = ProductDetailScreenViewController(nibName: nil, bundle: nil)
        let interactor = ProductDetailScreenInteractor()
        let router = ProductDetailScreenRouter()
        let presenter = ProductDetailScreenPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}

extension ProductDetailScreenRouter: ProductDetailScreenWireframeProtocol {

}
