//
//  ProductDetailScreenRouter.swift
//  PA Store
//
//  Created Haroon Shoukat on 23/01/2024.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Hasnain Kanji
//

import UIKit

final class ProductDetailScreenRouter {

    weak var viewController: UIViewController?

    deinit {
        printNgi("deinit ProductDetailScreenRouter")
    }

    static func createModule(product: DataProduct) -> UIViewController {

        // Change to get view from storyboard if not using progammatic UI
        let storyboard = getStoryBoard(.userAuthentication)
        let view = storyboard.instantiateViewController(ofType: ProductDetailScreenViewController.self)
        
        let interactor = ProductDetailScreenInteractor()
        let router = ProductDetailScreenRouter()
        let presenter = ProductDetailScreenPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        presenter.product = product
        
        return view
    }
}

extension ProductDetailScreenRouter: ProductDetailScreenWireframeProtocol {
    func gotoImageCapturePage(product: DataProduct) {
        let vc = UploadImageScreenRouter.createModule(product: product)
        self.viewController?.navigationController?.setViewControllers([vc], animated: true)
    }
}
